# Generated by Django 2.1.5 on 2020-01-14 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_car_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_img',
            new_name='img',
        ),
    ]
